# CMake generated Testfile for 
# Source directory: /code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi
# Build directory: /code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(st_hcm_srv "/code/lws/libwebsockets/scripts/ctest-background.sh" "hcm_srv" "/code/lws/libwebsockets/bin/lws-minimal-http-server-tls" "--port" "7670")
set_tests_properties(st_hcm_srv PROPERTIES  FIXTURES_SETUP "hcm_srv" TIMEOUT "800" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-server/minimal-http-server-tls")
add_test(ki_hcm_srv "/code/lws/libwebsockets/scripts/ctest-background-kill.sh" "hcm_srv" "lws-minimal-http-server-tls" "--port" "7670")
set_tests_properties(ki_hcm_srv PROPERTIES  FIXTURES_CLEANUP "hcm_srv")
add_test(st_hcmp_srv "/code/lws/libwebsockets/scripts/ctest-background.sh" "hcmp_srv" "/code/lws/libwebsockets/bin/libwebsockets-test-server" "-s" "-r" "/code/lws/libwebsockets/destdir/usr/local/share/libwebsockets-test-server/" "--port" "17670")
set_tests_properties(st_hcmp_srv PROPERTIES  FIXTURES_SETUP "hcmp_srv" TIMEOUT "800" WORKING_DIRECTORY ".")
add_test(ki_hcmp_srv "/code/lws/libwebsockets/scripts/ctest-background-kill.sh" "hcmp_srv" "libwebsockets-test-server" "--port" "17670")
set_tests_properties(ki_hcmp_srv PROPERTIES  FIXTURES_CLEANUP "hcmp_srv")
add_test(http-client-multi "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-l" "--port" "7670" "-d" "1151")
set_tests_properties(http-client-multi PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-h1 "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--h1" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-h1 PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-p" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-h1-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--h1" "-p" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-h1-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-stag "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-s" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-stag PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-stag-h1 "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--h1" "-s" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-stag-h1 PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-stag-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-p" "-s" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-stag-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-stag-h1-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--h1" "-p" "-s" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-stag-h1-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-restrict-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-d1151" "--limit" "1" "-p" "-l" "--port" "7670")
set_tests_properties(http-client-multi-restrict-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-restrict-h1-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-d1151" "--limit" "1" "--h1" "-p" "-l" "--port" "7670")
set_tests_properties(http-client-multi-restrict-h1-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-restrict-stag-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-d1151" "--limit" "1" "-p" "-s" "-l" "--port" "7670")
set_tests_properties(http-client-multi-restrict-stag-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-restrict-stag-h1-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "-d1151" "--limit" "1" "--h1" "-p" "-s" "-l" "--port" "7670")
set_tests_properties(http-client-multi-restrict-stag-h1-pipe PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-restrict-nopipe-fail "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--limit" "1" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-restrict-nopipe-fail PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WILL_FAIL "TRUE" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-restrict-h1-nopipe-fail "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--limit" "1" "--h1" "-l" "--port" "7670" "-d1151")
set_tests_properties(http-client-multi-restrict-h1-nopipe-fail PROPERTIES  FIXTURES_REQUIRED "hcm_srv" TIMEOUT "50" WILL_FAIL "TRUE" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "-l" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post-h1 "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "--h1" "-l" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post-h1 PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "-p" "-l" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post-pipe PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post-h1-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "--h1" "-p" "-l" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post-h1-pipe PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post-stag "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "-s" "-l" "-d1151" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post-stag PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post-stag-h1 "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "--h1" "-d1151" "-s" "-l" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post-stag-h1 PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post-stag-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "-p" "-s" "-l" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post-stag-pipe PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
add_test(http-client-multi-post-stag-h1-pipe "/code/lws/libwebsockets/bin/lws-minimal-http-client-multi" "--post" "--h1" "-p" "-s" "-l" "--port" "17670" "-d1151")
set_tests_properties(http-client-multi-post-stag-h1-pipe PROPERTIES  FIXTURES_REQUIRED "hcmp_srv" TIMEOUT "20" WORKING_DIRECTORY "/code/lws/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-multi")
